### ISSUE TITLE
Indicate previously-pro games

### ISSUE THREAD

**Issue by jeremyBanks** [stadians/stadians#12]
We probably shouldn't use this as a sort criteria, but we should indicate games that were previously available on Stadia Pro, as users are more likely to have them. We don't currently have this data, but we could start getting capturing it and backfill using my own library.

Here's a potential design for the labels.

![](https://user-images.githubusercontent.com/18020/92048999-26f8d200-ed57-11ea-8b05-4276729264d3.png)

```css
            main st-games st-game st-pro {
              color: #A66;
              background-color: #300000;
              font-size: 8px;
              text-align: right;
            }

            main st-games st-game st-pro:before {
              text-align: left;
              content: "previously ";
              display: block;
            }
```

It sounds like additional subscriptions are coming to Stadia soon; we'll see if they use the same claimable system or not.
